# Generated by Django 5.1.6 on 2025-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(),
        ),
    ]
