# Generated by Django 5.1.6 on 2025-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
